version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo ${ENVIRONMENT}
      - node --version
      - npm --version
      - npm install
      - SLS_DEBUG=1
  build:
    commands:
      - npm run build
      - npm run deploy:domain
      - npm run deploy:${ENVIRONMENT}
