service: patient-api

plugins:
  - serverless-domain-manager
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-pseudo-parameters
  - serverless-dotenv-plugin

custom:
  domains:
    development: api.gracemedicalvillagedev.com
    production: api.gracemedicalvillage.com
  certificateName:
    development: '*.gracemedicalvillagedev.com'
    production: '*.gracemedicalvillage.com'
  customDomain:
    domainName: ${self:custom.domains.${self:custom.stage}}
    basePath: ''
    certificateName: ${self:custom.certificateName.${self:custom.stage}}
    createRoute53Record: true
    endpointType: edge
    securityPolicy: tls_1_2
    stage: ${self:custom.stage}
  deployTable: false
  dynamodb:
    start:
      dir: offline
      inMemory: true
      migrate: true
      seed: true
    migration:
      dir: './resources/dynamoTable.json'
      port: 8000
    seed:
      patients:
        sources:
          - table: patients
            sources: [./resources/patients.json]
    stages:
      - local
      - test
  prefix: gmv
  serverless-offline:
    httpPort: 4000
  stage: ${opt:stage, self:provider.stage}
  tableName: patients

package:
  individually: true

provider:
  name: aws
  region: us-east-1
  runtime: nodejs12.x
  stage: ${provider.stage, 'development'}
  environment:
    stage: ${self:custom.stage}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: 'arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/${self:custom.tableName}'
  tracing:
    apigateway: true
    lambda: true

functions:
  get-patient-data:
    handler: build/get.main
    events:
      - http:
          path: patient
          method: get
          cors: false
          authorizer: aws_iam

  query-patient-data:
    handler: build/query.main
    events:
      - http:
          path: patients
          method: get
          cors: false
          authorizer: aws_iam

  put-patient-data:
    handler: build/put.main
    events:
      - http:
          path: patient
          method: post
          cors: false
          authorizer: aws_iam

  update-patient-data:
    handler: build/update.main
    events:
      - http:
          path: patient
          method: put
          cors: false
          authorizer: aws_iam

  delete-patient-data:
    handler: build/delete.main
    events:
      - http:
          path: patient
          method: delete
          cors: false
          authorizer: aws_iam

resources:
  Conditions:
    DeployPatientsTable:
      Fn::Equals:
        - ${self:custom.deployTable}
        - true

  Resources:
    patientsTable:
      Type: AWS::DynamoDB::Table
      Condition: DeployPatientsTable
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: key
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: key
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
