-- condition --
insert into condition (condition_name)
values ('Asthma'),
       ('Back Pain'),
       ('Diabetes'),
       ('GERD'),
       ('High Cholesterol'),
       ('Hypertension'),
       ('Hypothyroidism'),
       ('Joint Pain'),
       ('Abdominal Pain'),
       ('Anemia'),
       ('COPD'),
       ('Hyperthyroidism'),
       ('Prediabetes'),
       ('Skin Condition'),
       ('Obesity');

-- medication_category --
insert into medication_category (name)
values ('Antibiotics/Antivirals'),
       ('Antihistamine/Decongestant/Cough'),
       ('AntiHypertensive/Diuretic'),
       ('AntiEpileptic/AntiParkinson'),
       ('AntiPsychotics/AntiDepressants'),
       ('AntiSpasmodic/AntiCholenergic'),
       ('Cardiac'),
       ('Children Antibiotics'),
       ('Children Antihistamine/Decongestant/Cough/Suspension/Spray'),
       ('Children Pain Tabs'),
       ('Children Pain Suspension/Drops'),
       ('Children Vitamins'),
       ('Cholesterol'),
       ('Diabetes'),
       ('Gastric'),
       ('Glucorticoids/Corticosteriods'),
       ('Injectables'),
       ('Muscle Relaxant'),
       ('Ophthalmics/Optics'),
       ('Pain'),
       ('Respiratory'),
       ('Topicals (General)'),
       ('Topicals (Prescription)'),
       ('Urinary'),
       ('Vaginal'),
       ('Vitamins');

-- medication --
insert into medication (category_id, name, strength)
values ((select id from medication_category where name = 'Pain'), 'Acetaminophen', '500 mg'),
       ((select id from medication_category where name = 'Pain'), 'Acetaminophen', '650 mg'),
       ((select id from medication_category where name = 'Pain'), 'Ibuprofen', '200 mg'),
       ((select id from medication_category where name = 'Pain'), 'Ibuprofen', '400 mg'),
       ((select id from medication_category where name = 'Pain'), 'Ibuprofen', '600 mg'),
       ((select id from medication_category where name = 'Pain'), 'Ibuprofen', '800 mg'),
       ((select id from medication_category where name = 'Pain'), 'Meloxicam', '7.5 mg'),
       ((select id from medication_category where name = 'Pain'), 'Meloxicam', '15 mg'),
       ((select id from medication_category where name = 'Pain'), 'Naproxen Sodium', '220 mg'),
       ((select id from medication_category where name = 'Gastric'), 'Calcium Carbonate', '500 mg'),
       ((select id from medication_category where name = 'Gastric'), 'Dicyclomine ', '10 mg'),
       ((select id from medication_category where name = 'Gastric'), 'Docusate Sodium', '100 mg'),
       ((select id from medication_category where name = 'Gastric'), 'Milk of Magnesia', '0'),
       ((select id from medication_category where name = 'Gastric'), 'Famotidine', '20 mg '),
       ((select id from medication_category where name = 'Gastric'), 'Omeprazole', '20 mg'),
       ((select id from medication_category where name = 'Gastric'), 'Ordanestron', '4 mg'),
       ((select id from medication_category where name = 'Gastric'), 'Promethazine HCI ', '25 mg'),
       ((select id from medication_category where name = 'Antibiotics/Antivirals'), 'Acyclovir ', '200 mg'),
       ((select id from medication_category where name = 'Antibiotics/Antivirals'), 'Amoxicillin', '125 mg'),
       ((select id from medication_category where name = 'Antibiotics/Antivirals'), 'Amoxicillin', '500 mg'),
       ((select id from medication_category where name = 'Antibiotics/Antivirals'), 'Augmentin ', '500 mg/125mg'),
       ((select id from medication_category where name = 'Antibiotics/Antivirals'), 'Azithromycin Z Packs & Tabs',
        '250 mg'),
       ((select id from medication_category where name = 'Antibiotics/Antivirals'), 'Cephalexin', '500 mg'),
       ((select id from medication_category where name = 'Antibiotics/Antivirals'), 'CIprofloxacin', '500 mg'),
       ((select id from medication_category where name = 'Antibiotics/Antivirals'), 'Clindamycin HCI', '150 mg'),
       ((select id from medication_category where name = 'Antibiotics/Antivirals'), 'Doxycycline Hyclate ', '100 mg'),
       ((select id from medication_category where name = 'Antibiotics/Antivirals'), 'Fluconazole', '150 mg'),
       ((select id from medication_category where name = 'Antibiotics/Antivirals'), 'Metronidazole (Flagyl)', '250 mg'),
       ((select id from medication_category where name = 'Antibiotics/Antivirals'), 'SMZ/TMP - SS', '400/80 mg'),
       ((select id from medication_category where name = 'Antibiotics/Antivirals'), 'SMZ/TMP - DS', '800/160mg'),
       ((select id from medication_category where name = 'Antibiotics/Antivirals'), 'Tinidazole', '500 mg'),
       ((select id from medication_category where name = 'Antihistamine/Decongestant/Cough'), 'Cetirizine', '10 mg'),
       ((select id from medication_category where name = 'Antihistamine/Decongestant/Cough'),
        'Chlorpheniramine  Maleate', '4 mg'),
       ((select id from medication_category where name = 'Antihistamine/Decongestant/Cough'), 'Diphenhydramine HCI',
        '25 mg'),
       ((select id from medication_category where name = 'Antihistamine/Decongestant/Cough'), 'Flucatisone Propionate',
        '50 mcg'),
       ((select id from medication_category where name = 'Antihistamine/Decongestant/Cough'),
        'Guaifenesin ( Regular & DM)', '100 mg/5ml'),
       ((select id from medication_category where name = 'Antihistamine/Decongestant/Cough'), 'Guaifenesin ', '400 mg'),
       ((select id from medication_category where name = 'Antihistamine/Decongestant/Cough'),
        'Guaifenesin/Phenylephrine HCI', '400mg/10mg'),
       ((select id from medication_category where name = 'Antihistamine/Decongestant/Cough'), 'Loratadine ', '10 mg'),
       ((select id from medication_category where name = 'Antihistamine/Decongestant/Cough'),
        'Nasal Spray/Saline Nasal Spray', '0'),
       ((select id from medication_category where name = 'AntiHypertensive/Diuretic'), 'Atenolol', '50 mg'),
       ((select id from medication_category where name = 'AntiHypertensive/Diuretic'), 'Amlodipine', '10 mg'),
       ((select id from medication_category where name = 'AntiHypertensive/Diuretic'), 'Glipizide', '5 mg'),
       ((select id from medication_category where name = 'AntiHypertensive/Diuretic'), 'Furosemide', '40 mg'),
       ((select id from medication_category where name = 'AntiHypertensive/Diuretic'), 'HCTZ', '12.5 mg'),
       ((select id from medication_category where name = 'AntiHypertensive/Diuretic'), 'HCTZ', '25 mg'),
       ((select id from medication_category where name = 'AntiHypertensive/Diuretic'), 'Lisinopril', '5 mg'),
       ((select id from medication_category where name = 'AntiHypertensive/Diuretic'), 'Lisinopril', '10 mg'),
       ((select id from medication_category where name = 'AntiHypertensive/Diuretic'), 'Lisinopril', '20 mg'),
       ((select id from medication_category where name = 'AntiHypertensive/Diuretic'), 'Metopropol', '25 mg'),
       ((select id from medication_category where name = 'AntiHypertensive/Diuretic'), 'Metopropol', '50 mg'),
       ((select id from medication_category where name = 'AntiHypertensive/Diuretic'), 'Propranolol', '20 mg'),
       ((select id from medication_category where name = 'AntiHypertensive/Diuretic'), 'Propranolol', '10 mg'),
       ((select id from medication_category where name = 'AntiEpileptic/AntiParkinson'), 'Gabapentin', '100 mg'),
       ((select id from medication_category where name = 'AntiEpileptic/AntiParkinson'), 'Gabapentin', '300 mg'),
       ((select id from medication_category where name = 'AntiPsychotics/AntiDepressants'), 'Fluoxetine (Prozac)',
        '20 mg'),
       ((select id from medication_category where name = 'AntiPsychotics/AntiDepressants'), 'Sertraline HCI (Zoloft)',
        '25 mg'),
       ((select id from medication_category where name = 'AntiPsychotics/AntiDepressants'), 'Sertraline HCI (Zoloft)',
        '50 mg'),
       ((select id from medication_category where name = 'AntiPsychotics/AntiDepressants'), 'Trazodone HCI', '50 mg'),
       ((select id from medication_category where name = 'AntiPsychotics/AntiDepressants'), 'Trazodone HCI', '150 mg'),
       ((select id from medication_category where name = 'AntiSpasmodic/AntiCholenergic'), 'Ordanestron (Zofran)',
        '4 mg'),
       ((select id from medication_category where name = 'Cardiac'), 'Amlodipine', '5 mg'),
       ((select id from medication_category where name = 'Cardiac'), 'Amlodipine', '10 mg'),
       ((select id from medication_category where name = 'Cholesterol'), 'Atorvastatin: Lipitor', '10 mg'),
       ((select id from medication_category where name = 'Cholesterol'), 'Atorvastatin: Lipitor', '40 mg'),
       ((select id from medication_category where name = 'Cholesterol'), 'Rosuvastatin Calcium: Crestor', '10 mg'),
       ((select id from medication_category where name = 'Cholesterol'), 'Rosuvastatin Calcium: Crestor', '40 mg'),
       ((select id from medication_category where name = 'Cholesterol'), 'Simvastatin: Zocar ', '20 mg'),
       ((select id from medication_category where name = 'Diabetes'), 'Glipizide', '5 mg'),
       ((select id from medication_category where name = 'Diabetes'), 'Glipizide', '10 mg'),
       ((select id from medication_category where name = 'Diabetes'), 'Metformin HCI', '500 mg'),
       ((select id from medication_category where name = 'Diabetes'), 'Metformin HCI', '1000 mg'),
       ((select id from medication_category where name = 'Diabetes'), 'Metformin', '500 mg'),
       ((select id from medication_category where name = 'Glucorticoids/Corticosteriods'), 'Allopurinol', '100 mg'),
       ((select id from medication_category where name = 'Glucorticoids/Corticosteriods'), 'Prednisone', '5 mg'),
       ((select id from medication_category where name = 'Glucorticoids/Corticosteriods'), 'Prednisone', '10 mg'),
       ((select id from medication_category where name = 'Glucorticoids/Corticosteriods'), 'Prednisone', '20 mg'),
       ((select id from medication_category where name = 'Muscle Relaxant'), 'Cyclobenzaprine HCI', '10 mg'),
       ((select id from medication_category where name = 'Ophthalmics/Optics'), 'Artificial Tears', '0'),
       ((select id from medication_category where name = 'Ophthalmics/Optics'), 'Ciprofloxacin Solution ', '0.003'),
       ((select id from medication_category where name = 'Ophthalmics/Optics'), 'Gentamicin Sulfate', '5 ml'),
       ((select id from medication_category where name = 'Ophthalmics/Optics'), 'Ofloxacin ', '0.003'),
       ((select id from medication_category where name = 'Ophthalmics/Optics'), 'Polyvinyl Alcohol Eye Drops', '0.014'),
       ((select id from medication_category where name = 'Ophthalmics/Optics'), 'Tetrahydrozoline (0.05%)', '15 ml'),
       ((select id from medication_category where name = 'Respiratory'), 'Albuterol Sulfate 0.083%',
        '2.5mg/3ml Inhalation Solution'),
       ((select id from medication_category where name = 'Respiratory'), 'Albuterol Sulfate Inhalation Aersol',
        '90 mcg'),
       ((select id from medication_category where name = 'Respiratory'), 'Albuterol Sulfate Inhalers (Ventolin)', '0'),
       ((select id from medication_category where name = 'Respiratory'), 'Salbucort', '100 mcg'),
       ((select id from medication_category where name = 'Respiratory'), 'Singulair (Montelukast Sodium)', '4 mg'),
       ((select id from medication_category where name = 'Respiratory'), 'Singulair (Montelukast Sodium)', '10 mg'),
       ((select id from medication_category where name = 'Topicals (General)'), 'Triple Antibiotic', '0'),
       ((select id from medication_category where name = 'Topicals (General)'), 'Clotrimazole (Fungal)', '0.01'),
       ((select id from medication_category where name = 'Topicals (General)'), 'Hydrocortisone', '0.01'),
       ((select id from medication_category where name = 'Topicals (General)'), 'Muscle Rub', '0'),
       ((select id from medication_category where name = 'Topicals (General)'), 'Petroleum Jelly ', '0'),
       ((select id from medication_category where name = 'Topicals (Prescription)'), 'Triamcinolone (80mg)', '0.001'),
       ((select id from medication_category where name = 'Topicals (Prescription)'), 'Hydrocortisione', '0.025'),
       ((select id from medication_category where name = 'Urinary'), 'Tamsulosin', '0.4 mg'),
       ((select id from medication_category where name = 'Vaginal'), 'Clogtrimazole - Vaginal', '0.01'),
       ((select id from medication_category where name = 'Vaginal'), 'Fluconazole (Diflucan)', '150 mg'),
       ((select id from medication_category where name = 'Vitamins'), 'Adult', '0'),
       ((select id from medication_category where name = 'Vitamins'), 'D3 - Cholecalciferol', '50,000 IU'),
       ((select id from medication_category where name = 'Vitamins'), 'D3 - Cholecalciferol', '5,000 IU'),
       ((select id from medication_category where name = 'Vitamins'), 'Folic Acit', '800 mcg'),
       ((select id from medication_category where name = 'Vitamins'), 'Iron Tabs', '325 Mg'),
       ((select id from medication_category where name = 'Vitamins'), 'Pre-Natal', '0'),
       ((select id from medication_category where name = 'Injectables'), 'Cefazolin - Powder', '1 gm'),
       ((select id from medication_category where name = 'Injectables'), 'Ceftriazone Sodium - Powder: Rocephen',
        '1 gm'),
       ((select id from medication_category where name = 'Injectables'), 'Vitamin B 12: cyancocbalamin', '10 ml'),
       ((select id from medication_category where name = 'Injectables'), 'Dexamethasone', '4mg'),
       ((select id from medication_category where name = 'Injectables'), 'Dexamethasone', '5ml'),
       ((select id from medication_category where name = 'Injectables'), 'Diphenhydramine HCI', '50mg/ml'),
       ((select id from medication_category where name = 'Injectables'), 'Ketorolac ', '60mg/2ml'),
       ((select id from medication_category where name = 'Injectables'), 'Lidocaine', '50mg'),
       ((select id from medication_category where name = 'Injectables'), 'Lidocaine', '500mg'),
       ((select id from medication_category where name = 'Children Antibiotics'), 'Amoxicillin for O/S', '125mg/5ml'),
       ((select id from medication_category where name = 'Children Antibiotics'), 'Amoxicillin for O/S', '250mg/100ml'),
       ((select id from medication_category where name = 'Children Antibiotics'), 'Amoxicillin for O/S', '250mg/150ml'),
       ((select id from medication_category where name = 'Children Antibiotics'), 'Amoxicillin for O/S', '400mg/5ml'),
       ((select id from medication_category where name = 'Children Antibiotics'), 'Augmentin for O/S', '200mg/28.5ml'),
       ((select id from medication_category where name = 'Children Antibiotics'), 'Augmentin ', '500 mg'),
       ((select id from medication_category where name = 'Children Antibiotics'), 'Augmentin ', '125mg'),
       ((select id from medication_category where name = 'Children Antihistamine/Decongestant/Cough/Suspension/Spray'),
        'Cetirizine (Zrytec)', '1 mg/ml'),
       ((select id from medication_category where name = 'Children Antihistamine/Decongestant/Cough/Suspension/Spray'),
        'Dimetapp Cough & Cold - Day', '6+ Years'),
       ((select id from medication_category where name = 'Children Antihistamine/Decongestant/Cough/Suspension/Spray'),
        'Dimetapp Cough & Cold - Night', '6+ Years'),
       ((select id from medication_category where name = 'Children Antihistamine/Decongestant/Cough/Suspension/Spray'),
        'Benedryl:Equate Children''s Allergy (6-11 years)',
        '12.5mg/5ml'),
       ((select id from medication_category where name = 'Children Antihistamine/Decongestant/Cough/Suspension/Spray'),
        'Equate Throat Relief Pops', 'Pectin 10 mg'),
       ((select id from medication_category where name = 'Children Antihistamine/Decongestant/Cough/Suspension/Spray'),
        'Fluticasone Propionate', '50 mcg'),
       ((select id from medication_category where name = 'Children Antihistamine/Decongestant/Cough/Suspension/Spray'),
        'Loratidine - Children''s',
        '5mg/ml'),
       ((select id
         from medication_category
         where name = 'Children Antihistamine/Decongestant/Cough/Suspension/Spray'),
        'Zarbees Cough & Cold - Day & Night', '6+ Years'),
       ((select id from medication_category where name = 'Children Pain Tabs'), 'Ibuprofen', '100 mg'),
       ((select id from medication_category where name = 'Children Pain Tabs'), 'Tylenol ', '160 mg'),
       ((select id from medication_category where name = 'Children Pain Suspension/Drops'),
        'Motrin: Children''s Ibuprofen', '100mg/5ml'),
       ((select id from medication_category where name = 'Children Pain Suspension/Drops'),
        'Infant Ibuprofen (6-23 months)', '50mg/1.25ml'),
       ((select id from medication_category where name = 'Children Pain Suspension/Drops'),
        'Children''s Tylenol - Susp',
        '160 mg/5ml'),
       ((select id from medication_category where name = 'Children Pain Suspension/Drops'),
        'Infant Tylenol - Susp', '160 mg/5ml'),
       ((select id from medication_category where name = 'Children Pain Suspension/Drops'),
        'Infant Tylenol - Drops', '160 mg/5ml'),
       ((select id from medication_category where name = 'Children Vitamins'),
        'Children''s Multi w/o Iron - Chewable', '0'),
       ((select id from medication_category where name = 'Children Vitamins'), 'Infant Multi w/ Iron', '0');


-- metric --
insert
into metric (metric_name, unit_of_measure, uom, format, pattern, map, min_value, max_value, archived)
values ('Blood Pressure', 'millimeters of mercury', 'mm/Hg', '120/80', '^([1-9]|[1-9]\d+)/([1-9]|[1-9]\d+)$', true, 1, 500, false),
       ('Blood Sugar', 'milligrams per deciliter', 'mg/dL', '120', '^([1-9]|[1-9]\d+)(\.\d+)?$', true, 20, 400, true),
       ('Cholesterol (Total)', 'milligrams per deciliter', 'mg/dL', '240', '^([1-9]|[1-9][0-9]{1,2})$', true, 20, 300, false),
       ('Heart Rate', 'beats per minute', 'bpm', '55', '^([1-9]|[1-9][0-9]{1,2})$', false, 1, 500, false),
       ('Height', 'inches', 'in', '63', '^([1-9]|[1-9]\d+)(\.\d+)?$', true, 4, 96, false),
       ('Hemoglobin (A1c)', 'milligrams per deciliter', '%', '7.0', '^([1-9]|[1-9]\d+)(\.\d+)?$', true, 0.1, 20.0, false),
       ('Hip Size', 'inches', 'in', '28', '^([1-9]|[1-9]\d+)(\.\d+)?$', false, 4, 100, false),
       ('Last Menstrual Period', '', '', '2000-12-31', '(\d{4})-(\d{2})-(\d{2})', false, null, null, false),
       ('Pain', '', '', '5', '^\b([0-9]|10)\b$', false, 0, 10, false),
       ('PulseOx', 'Blood Oxygen Level', 'SpO2', '75', '^([1-9]|[1-9]\d+)(\.\d+)?$', false, 50, 100, false),
       ('Respiration Rate', 'breaths per minute', 'bpm', '20', '^([1-9]|[1-9]\d+)(\.\d+)?$', false, 1, 240, false),
       ('Temperature', 'degrees fahrenheit', '°F', '101.5', '^([1-9]|[1-9]\d+)(\.\d+)?$', false, 60, 120, false),
       ('Waist Size', 'inches', 'in', '38', '^([1-9]|[1-9]\d+)(\.\d+)?$', false, 4, 100, false),
       ('Weight', 'pounds', 'lb', '195', '^([1-9]|[1-9]\d+)(\.\d+)?$', false, 4, 800, false),
       ('Blood Sugar (Fasting)', 'milligrams per deciliter', 'mg/dL', '120', '^([1-9]|[1-9]\d+)(\.\d+)?$', true, 20, 400, false),
       ('Blood Sugar (Nonfasting)', 'milligrams per deciliter', 'mg/dL', '120', '^([1-9]|[1-9]\d+)(\.\d+)?$', true, 20, 400, false);
